from django.db import models

class Aprendizagem(models.Model):
    CD_ALUNO = models.BigIntegerField(db_column='cd_aluno', primary_key=True)
    CD_DOCUMENTO = models.BigIntegerField(db_column='cd_documento')
    CD_AVALIACAO = models.IntegerField(db_column='cd_avaliacao')
    DC_TECNOLOGIA_PUBLICACAO = models.CharField(max_length=50, db_column='dc_tecnologia_publicacao')
    FL_EXTRA = models.BooleanField(db_column='fl_extra')
    CD_PAIS = models.IntegerField(db_column='cd_pais')
    NM_PAIS = models.CharField(max_length=100, db_column='nm_pais')
    CD_ESTADO = models.IntegerField(db_column='cd_estado')
    NM_ESTADO = models.CharField(max_length=100, db_column='nm_estado')
    CD_REGIONAL = models.IntegerField(db_column='cd_regional')
    NM_REGIONAL = models.CharField(max_length=100, db_column='nm_regional')
    CD_MUNICIPIO = models.IntegerField(db_column='cd_municipio')
    NM_MUNICIPIO = models.CharField(max_length=100, db_column='nm_municipio')
    CD_ESCOLA = models.IntegerField(db_column='cd_escola')
    NM_ESCOLA = models.CharField(max_length=100, db_column='nm_escola')
    CD_LOCALIZACAO = models.IntegerField(db_column='cd_localizacao')
    DC_LOCALIZACAO = models.CharField(max_length=100, db_column='dc_localizacao')
    CD_TURMA = models.CharField(max_length=20, db_column='cd_turma')
    CD_TURMA_INSTITUCIONAL = models.BigIntegerField(db_column='cd_turma_institucional')
    NM_TURMA = models.CharField(max_length=100, db_column='nm_turma')
    CD_TURNO = models.IntegerField(db_column='cd_turno')
    DC_TURNO = models.CharField(max_length=50, db_column='dc_turno')
    CD_REDE = models.IntegerField(db_column='cd_rede')
    DC_REDE = models.CharField(max_length=50, db_column='dc_rede')
    CD_ALUNO_INSTITUCIONAL = models.BigIntegerField(db_column='cd_aluno_institucional')
    CD_ALUNO_INEP = models.BigIntegerField(db_column='cd_aluno_inep')
    NM_ALUNO = models.CharField(max_length=100, db_column='nm_aluno')
    CD_ALUNO_NEC_ESPECIAL = models.IntegerField(db_column='cd_aluno_nec_especial')
    DC_ALUNO_NEC_ESPECIAL = models.CharField(max_length=50, db_column='dc_aluno_nec_especial')
    DC_CADERNO = models.CharField(max_length=50, db_column='dc_caderno')
    CD_INSTRUMENTO_CAED = models.BigIntegerField(db_column='cd_instrumento_caed')
    CD_DISCIPLINA = models.IntegerField(db_column='cd_disciplina')
    NM_DISCIPLINA = models.CharField(max_length=100, db_column='nm_disciplina')
    CD_ETAPA_APLICACAO = models.IntegerField(db_column='cd_etapa_aplicacao')
    DC_ETAPA_APLICACAO = models.CharField(max_length=100, db_column='dc_etapa_aplicacao')
    CD_ETAPA_AVALIADA = models.IntegerField(db_column='cd_etapa_avaliada')
    DC_ETAPA_AVALIADA = models.CharField(max_length=100, db_column='dc_etapa_avaliada')
    CD_ENSINO = models.IntegerField(db_column='cd_ensino')
    DC_ENSINO = models.CharField(max_length=100, db_column='dc_ensino')
    FL_PREVISTO = models.BooleanField(db_column='fl_previsto')
    FL_AVALIADO = models.BooleanField(db_column='fl_avaliado')
    DC_RESPOSTA = models.CharField(max_length=100, db_column='dc_resposta')
    NU_RESPOSTA = models.IntegerField(db_column='nu_resposta')
    NU_ACERTO = models.IntegerField(db_column='nu_acerto')
    NU_TOTAL = models.IntegerField(db_column='nu_total')
    TX_ACERTO = models.DecimalField(max_digits=5, decimal_places=2, db_column='tx_acerto')
    VL_PROFICIENCIA = models.DecimalField(max_digits=12, decimal_places=8, db_column='vl_proficiencia')
    VL_PROFICIENCIA_ERRO = models.DecimalField(max_digits=12, decimal_places=8, db_column='vl_proficiencia_erro')
    DC_PADRAO_DESEMPENHO = models.CharField(max_length=50, db_column='dc_padrao_desempenho')
    CD_HABILIDADE = models.CharField(max_length=50, db_column='cd_habilidade')
    NM_HABILIDADE = models.CharField(max_length=100, db_column='nm_habilidade')
    DC_HABILIDADE_ACERTO = models.CharField(max_length=50, db_column='dc_habilidade_acerto')
    DC_HABILIDADE_TOTAL = models.CharField(max_length=50, db_column='dc_habilidade_total')
    RP_COMPONENTE_CURRICULAR = models.CharField(max_length=100, db_column='rp_componente_curricular')
    RP_GABARITO = models.CharField(max_length=100, db_column='rp_gabarito')
    DC_ITENS = models.CharField(max_length=100, db_column='dc_itens')
    NM_HABILIDADE_POR_ITEM = models.CharField(max_length=100, db_column='nm_habilidade_por_item')
    DC_ITENS_ACERTO = models.CharField(max_length=50, db_column='dc_itens_acerto')
    CD_GRUPO = models.CharField(max_length=50, db_column='cd_grupo')
    NM_GRUPO = models.CharField(max_length=100, db_column='nm_grupo')

    class Meta:
        db_table = 'avaliacoes'  # Nome da tabela no banco de dados